name: jetleaf_pod
description: Core module for dependency injection and pod lifecycle management.
version: 1.0.0+2

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_pod
issue_tracker: https://github.com/jetleaf/jetleaf_pod/issues
documentation: https://jetleaf.hapnium.com/docs/pod

topics:
  - ioc
  - dependency-injection
  - pod
  - jetleaf
  - lifecycle

keywords:
  - ioc
  - dependency-injection
  - service-locator
  - pod
  - jetleaf

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: 
    path: ../jetleaf_lang
  jetleaf_logging: 
    path: ../jetleaf_logging
  jetleaf_convert: 
    path: ../jetleaf_convert
  jetleaf_utils: 
    path: ../jetleaf_utils
  jetleaf_env: 
    path: ../jetleaf_env

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0