name: jetleaf_pod
description: Core module for dependency injection and pod lifecycle management.
version: 1.0.1+2

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_pod
issue_tracker: https://github.com/jetleaf/jetleaf_pod/issues
documentation: https://jetleaf.hapnium.com/docs/pod

topics:
  - ioc
  - dependency-injection
  - pod
  - jetleaf
  - lifecycle

keywords:
  - ioc
  - dependency-injection
  - service-locator
  - pod
  - jetleaf

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.0.1+1
  jetleaf_logging: ^1.0.1+1
  jetleaf_convert: ^1.0.1+1
  jetleaf_utils: ^1.0.1+1
  jetleaf_env: ^1.0.1+1

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0